services:
  mysql:
    build:
      context: .
      dockerfile: services/mysql/Dockerfile
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: .docker/services/app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - mysql

volumes:
  db_data: